services:
  markitos-golang-service-postgres-for-access:
    image: postgres:latest
    container_name: markitos-golang-service-postgres-for-access
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    networks:
      markitos-network-for-access:

networks:
  markitos-network-for-access:
    driver: bridge